name: Build Texts App Desktop

on:
  push:
    paths:
      - 'trigger.txt'

jobs:
  build:
    runs-on: macos-11

    timeout-minutes: 60

    env:
      CERT_P12_PATH: "/tmp/textshq.p12"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Store codesigning certificate locally
        run: echo ${{ secrets.CERT_P12 }} | base64 --decode > $CERT_P12_PATH

      - name: Build
        run: ./build.sh
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          CERT_P12_PASS: ${{ secrets.CERT_P12_PASS }}

      - name: Upload packages
        uses: actions/upload-artifact@v2
        with:
          name: packages
          path: texts-app-desktop/packaged/

