name: Build Texts App Desktop

on:
  push:
    paths:
      - 'trigger.txt'

jobs:
  build:
    runs-on: macos-11

    timeout-minutes: 80

    env:
      # Warnings are treated as errors if CI is true
      CI: ""
      # Fixes electron-builder #3179 of EEXIST: file already exists for mac linkage
      USE_HARD_LINKS: false
      CERT_P12_PATH: "/tmp/textshq.p12"
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      CERT_P12_PASS: ${{ secrets.CERT_P12_PASS }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Store codesigning certificate locally
        run: echo ${{ secrets.CERT_P12 }} | base64 --decode > $CERT_P12_PATH

      - name: Init packages
        run: TEXTS_BUILD_STAGE=INIT ./build.sh

      - name: Cache packages node modules
        id: cache-package-modules
        uses: actions/cache@v2
        with:
          path: packages/*/node_modules
          key: packages-node-modules

      - name: Build packages
        run: TEXTS_BUILD_STAGE=BUILD ./build.sh

      - name: Upload packages
        uses: actions/upload-artifact@v2
        with:
          name: packages
          path: texts-app-desktop/packaged.tar.gz

